x-def-logging: &default-logging
  logging:
    driver: "loki"
    options:
      loki-url: "http://192.168.1.86:3100/loki/api/v1/push"
      loki-batch-size: "400"

services:
  voice-insight-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voice-insight-bot
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
    environment:
      - PYTHONUNBUFFERED=1
    
    volumes:
      - .:/root
      - /home/user/voice-insight-bot/files:/root/files
  
    command: ["python3", "main.py"]

    restart: unless-stopped

    <<: *default-logging
